"""
EVEN FIBONACCI NUMBERS
Problem 2
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5 ,8, 13, 21, 34, 55, 89,...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""
def even_fib_sum(limit=4000000):
    # first two fibonacci numbers
    a = 1
    b = 2
    
    sum = 0
    
    while b <= limit:
        if b % 2 == 0:
            sum += b
        # temp = a
        # a = b
        # b = temp + b
        a, b = b, a + b   # generate the next fibonacci number
    return sum

print("The sum of even-valued Fibonacci numbers less than 4000000 is: ", even_fib_sum())
